networks:
  ticket-tech-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.51.0.0/16
volumes:
  ticket_tech_pgdata:

services:
  ticket-tech-db:
    image: postgres:15
    container_name: ticket-tech-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ticket_tech_pgdata:/var/lib/postgresql/data
    networks:
      - ticket-tech-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8261:8261"
    networks:
      - ticket-tech-network
    deploy:
      resources:
        limits:
          memory: 1g

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "6666:6666"
    networks:
      - ticket-tech-network
    depends_on:
      - discovery-service
    deploy:
      resources:
        limits:
          memory: 1g

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8020:8020"
    networks:
      - ticket-tech-network
    depends_on:
      - discovery-service
      - gateway-service
      - ticket-tech-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ticket-tech-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SECRET: ${SECRET}
      EXP_TIME: ${EXP_TIME}

  language-service:
    build:
      context: ./language-service
    ports:
      - "8021:8021"
    networks:
      - ticket-tech-network
    depends_on:
      - discovery-service
      - gateway-service
      - ticket-tech-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ticket-tech-db:5432/language_db
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SECRET: ${SECRET}
      EXP_TIME: ${EXP_TIME}

  administration-service:
    build:
      context: ./administration-service
    ports:
      - "8022:8022"
    networks:
      - ticket-tech-network
    depends_on:
      - discovery-service
      - gateway-service
      - ticket-tech-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ticket-tech-db:5432/admin_db
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SECRET: ${SECRET}
      EXP_TIME: ${EXP_TIME}